### PR TITLE
Fix IKFastPlugin initialization. Fixes #1448

### LINKED ISSUE #1448: IKFast plugin not initialized correctly
### Description

We have a test failing sporadically after an IKfast update.
https://github.com/PilzDE/pilz_robots/blob/kinetic-devel/prbt_ikfast_manipulator_plugin/test/unittests/tst_prbt_ikfast_manipulator_plugin.cpp

My guess is that `IKFastKinematicsPlugin::computeRelativeTransform` does use an uninitialized RobotState, which can lead to errors.

An issue is also that above function returns true even if the computed transform is not well-defined.

### PR DESCRIPTION
**Pull request by martiniil**
- initialize values of RobotState in computeRelativeTransform()
- add tolerance for comparison to identity

### Description

see #1448

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extended the tutorials / documentation, if necessary [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Include a screenshot if changing a GUI
- [ ] Document API changes relevant to the user in the moveit/MIGRATION.md notes
- [ ] Created tests, which fail without this PR [reference](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/tests.html)
- [ ] Decide if this should be cherry-picked to other current ROS branches
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

File: moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp [hunk 1]
```diff
@@ -393,7 +396,7 @@ bool IKFastKinematicsPlugin::computeRelativeTransform(const std::string& from, c
   }
 
   transform = robot_state->getGlobalLinkTransform(from_link).inverse() * robot_state->getGlobalLinkTransform(to_link);
-  differs_from_identity = !transform.matrix().isIdentity();
+  differs_from_identity = !transform.matrix().isIdentity(RELATIVE_TRANSFORM_TOLERANCE);
```
Comment (rhaschke) [inline moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp]: Why do you think, we should change the default (machine) tolerance value here?

Comment (martiniil) [reply moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp]: Because we can avoid unnecessary computations, if we account for numerical errors. However I saw that the default precision is `1e-12`, which should be fine.
