### PR TITLE
Fix #868: calling service capability locks PlanningSceneMonitor

### LINKED ISSUE #868: 'Failed to fetch current robot state' when using the 'plan_kinematic_path' service
### Description

The 'plan_kinematic_path' service requires at least one second computation time and outputs the message 'Failed to fetch current robot state'. The issue has been introduced by the pull request #350 and the new line

```
+  // before we start planning, ensure that we have the latest robot state received...
+  context_->planning_scene_monitor_->waitForCurrentRobotState(ros::Time::now());
```

in moveit_ros/move_group/src/default_capabilities/plan_service_capability.cpp
While processing the computePlanService, the current state monitor is not able to process the incoming joint states in the callback function planning_scene_monitor::CurrentStateMonitor::jointStateCallback. Therefore waitForCurrentRobotState always waits until the maximum allowed time (by defaul 1 second) has passed and prints the error message 'Failed to fetch current robot state'.
The problem can be solved by adding a second spinning thread, i.e. 

```
ros::AsyncSpinner spinner(2);
```

in moveit_ros/move_group/src/move_group.cpp. However, I do not know if this would introduce new problems at other places. Note that the problem does not exist with the MoveGroupMoveAction capability because the action server does not block the spinning thread.

### Your environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04
* Source or Binary build? Applies to both as long as #350 is included.

### Steps to reproduce
I have added some debug print statements to highlight the issue, see the [diff](https://gist.github.com/avoelz/5095547bb3873d5549137a2e9eb3f883), then run

roslaunch *_moveit_config demo.launch 
for an arbitrary robot model with move_group/MoveGroupPlanService capability enabled

rosservice call /plan_kinematic_path "motion_plan_request: ..." 
for an arbitrary motion plan request

### Expected behaviour

Service plan_kinematic_path returns in few milliseconds with output similar to

```
[ INFO] [1524824641.260897825]: planning_scene_monitor::CurrentStateMonitor::jointStateCallback
[ INFO] [1524824641.460614270]: planning_scene_monitor::CurrentStateMonitor::jointStateCallback
[ INFO] [1524824641.660500520]: planning_scene_monitor::CurrentStateMonitor::jointStateCallback
[ INFO] [1524824641.790221505]: Received new planning service request...
[ INFO] [1524824641.860544618]: planning_scene_monitor::CurrentStateMonitor::jointStateCallback
[ERROR] [1524824641.861405290]: No group specified to plan for
[ INFO] [1524824641.861477559]: Elapsed time: 0.071 s
[ INFO] [1524824642.060578465]: planning_scene_monitor::CurrentStateMonitor::jointStateCallback
[ INFO] [1524824642.260910956]: planning_scene_monitor::CurrentStateMonitor::jointStateCallback
[ INFO] [1524824642.461013625]: planning_scene_monitor::CurrentStateMonitor::jointStateCallback
```

### Actual behaviour

Service plan_kinematic_path returns after approximately one second with output similar to

```
[ INFO] [1524824543.477195149]: planning_scene_monitor::CurrentStateMonitor::jointStateCallback
[ INFO] [1524824543.577266157]: planning_scene_monitor::CurrentStateMonitor::jointStateCallback
[ INFO] [1524824543.776860643]: planning_scene_monitor::CurrentStateMonitor::jointStateCallback
[ INFO] [1524824543.811930327]: Received new planning service request...
[ INFO] [1524824544.812130689]: Didn't received robot state (joint angles) with recent timestamp within 1 seconds.
Check clock synchronization if your are running ROS across multiple machines!
[ WARN] [1524824544.812195049]: Failed to fetch current robot state.
[ERROR] [1524824544.813068385]: No group specified to plan for
[ INFO] [1524824544.813148931]: Elapsed time: 1.001 s
[ INFO] [1524824544.813359534]: planning_scene_monitor::CurrentStateMonitor::jointStateCallback
[ INFO] [1524824544.976705795]: planning_scene_monitor::CurrentStateMonitor::jointStateCallback
[ INFO] [1524824545.077333781]: planning_scene_monitor::CurrentStateMonitor::jointStateCallback
```

One can see that in the second case the jointStateCallback is not executed as long as the planning request is processed.

### PR DESCRIPTION
**Pull request by rhaschke**
As described in https://github.com/ros-planning/moveit/issues/868#issuecomment-385127395, ROS service capabilities will essentially block the global event queue. Thus, key components as the PlanningSceneMonitor (and the associated CurrentStateMonitor) should use their own event queue and spinner to become independent of the global queue.

### CODE REVIEW

**Comment by v4hn** [comment]
I actually forgot about this issue.. Looks good!

However, there have been complains by users in the past when MoveIt classes start their own threads unconditionally.
I believe we should provide another constructor here to use a user-provided CallbackQueue instead.

**Comment by rhaschke** [comment]
Passing a user-provided CallbackQueue, will not stop creating a thread by the internal spinner.
I think there is no chance to avoid conflicts without another thread (as the main spinner thread blocks on the global callback queue). 
Regarding the complains: All action-server-based capabilities will spawn an own thread as well...

**Comment by rhaschke** [comment]
Would you prefer to pass a CallbackQueue or a NodeHandle (as in other locations of the API)?
NodeHandle might also change the namespace, which is undesirable...

**Comment by v4hn** [comment]
`NodeHandle` is definitely the more common interface for something like this, but then we have `root_nh_` as well as `nh_`.
We don't want to pass two handles (I guess), the alternatives being
(1) taking a root node-handle for the constructor, creating a private handle internally and copy the queue from the root nh we received
(2) pass the queue directly and set it for both nodes
(3) similar to MoveGroupInterface we could have an `Options` struct that can contain both node-handles

I would say (2) is the simplest option.

**Comment by rhaschke** [comment]
There is no problem in using (1). I think, it's not even necessary to copy the the event queue explicitly if we initialize the private handle from the root: `nh_(root_nh, "~")`.
However, passing a root handle with a custom/wrong namespace set, will probably break everything. Hence, option (2) might be safer.

**Comment by rhaschke** [comment]
@v4hn I added a new constructor to accept an external NodeHandle. Can you please review?

File: moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp [hunk 1]
```diff
@@ -171,6 +177,7 @@ planning_scene_monitor::PlanningSceneMonitor::~PlanningSceneMonitor()
   parent_scene_.reset();
   robot_model_.reset();
   rm_loader_.reset();
+  spinner_.stop();
```
Comment (v4hn) [inline moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp]: Is it well defined what happens if this was never started?

File: moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp [hunk 2]
```diff
@@ -120,34 +120,41 @@ const std::string planning_scene_monitor::PlanningSceneMonitor::MONITORED_PLANNI
...
+  root_nh_.setCallbackQueue(&queue_);
+  nh_.setCallbackQueue(&queue_);
+  spinner_.start();
+  initialize(scene);
+}
+
+planning_scene_monitor::PlanningSceneMonitor::PlanningSceneMonitor(
+    const planning_scene::PlanningScenePtr& scene, const robot_model_loader::RobotModelLoaderPtr& rm_loader,
+    const ros::NodeHandle& nh, const std::shared_ptr<tf2_ros::Buffer>& tf_buffer, const std::string& name)
+  : monitor_name_(name), nh_(nh, "~"), root_nh_(nh), spinner_(1, &queue_), tf_buffer_(tf_buffer), rm_loader_(rm_loader)
```
Comment (v4hn) [inline moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp]: Tested on kinetic:
```
$ cat src/mytest/src/mytest.cpp
#include <ros/ros.h>

int main(int argc, char **argv) {
  ros::init(argc, argv, "mytest");

  ros::NodeHandle nh;
  ros::NodeHandle pnh(nh, "~");
  return 0;
}
$ rosrun mytest mytest
terminate called after throwing an instance of 'ros::InvalidNameException'
  what():  Using ~ names with NodeHandle methods is not allowed.  If you want to use private names with the NodeHandle interface, construct a NodeHandle using a private name as its namespace.  e.g. ros::NodeHandle nh("~");  nh.getParam("my_private_name"); (name = [~])
Aborted (core dumped)
```

I guess you did not add a test for this?
Maybe they changed this in melodic, but I doubt it.

File: moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h [hunk 3]
```diff
@@ -143,6 +144,20 @@ class PlanningSceneMonitor : private boost::noncopyable
                        const std::shared_ptr<tf2_ros::Buffer>& tf_buffer = std::shared_ptr<tf2_ros::Buffer>(),
                        const std::string& name = "");
 
+  /** @brief Constructor
+   *  @param scene The scene instance to maintain up to date with monitored information
+   *  @param rml A pointer to a kinematic model loader
+   *  @param nh external parent NodeHandle
+   *         Ensure that this NodeHandle's CallbackQueue is different from the global queue and that
+   *         it is served by an external spinner!
```
Comment (v4hn) [inline moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h]: This mechanism can also be used to explicitly run in the global queue, if the user wants it that way (we did it for a long time and it's not necessarily a problem).
Can you change this to just state that the Monitors will be updated with the queue of this node handle?

File: moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp (hunk 1 above)
Comment (rhaschke) [reply moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp]: Yes. AsyncSpinner just doesn't do anything:
http://docs.ros.org/melodic/api/roscpp/html/spinner_8cpp_source.html#l00289

File: moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp (hunk 2 above)
Comment (rhaschke) [reply moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp]: Fixed.

**Comment by rhaschke** [comment]
@v4hn Is there anything left that keeps you from approving and merging this?
