### PR TITLE
Tranform Pilz goal pose and center point wrt. the planning frame

### LINKED ISSUE #3035: Pilz industrial motion planner ignores goal constraint frame_id
### Description

Hi, I'm using pilz_industrial_motion_planner to plan some trajectories interfacing directly with it through some calls to /move_group action server.

I noticed that if I plan with OMPL pipeline, I can set the goal constraint frame_id as any frame present in the planning scene (TF, collision objects sub-frames) and the planner correctly plan to the right goal as desired.

Instead planning with pilz_industrial_motion_planner pipeline:
* PTP simply ignores the goal constraint frame_id and instead it assumes that goal position and orientation constraints are respect to the robot model frame.
* LIN always fails reporting: 
```
[ INFO] [1643103242.859113763]: Using planning pipeline 'pilz_industrial_motion_planner'
[ INFO] [1643103242.859239956]: Generating LIN trajectory...
[ERROR] [1643103242.859357051]: Given frame (goal_link) is unequal to model frame(world)
[ERROR] [1643103242.859459598]: Failed to compute inverse kinematics for link: tool0 of goal pose
```
* CIRC I've not tested yet but I suppose there is some issue there too.

### Your environment
* ROS Distro: [Noetic]
* OS Version: Ubuntu 20.04
* Binary build
* 1.1.7

### Steps to reproduce
* Create a MotionPlanRequest with a goal constraint frame_id equal to a TF frame or collision object sub-frame present in the planning scene;
* Send a goal with that motion request to /move_group action server.

### Expected behaviour
Plan taking account of the goal constraint frame_id in the planning request as does OMPL.

### Actual behaviour
* PTP ignores the goal constraint frame_id.
* LIN always fails.
* CIRC not yet tested.

### PR DESCRIPTION
**Pull request by captain-yoshi**
### Description

Should fix #3035 (partially) and ros-planning/moveit_task_constructor/issues/411 by transforming the goal pose (CIRC, LIN and PTP) and the center point (CIRC) wrt. the planning frame.

Only computes the IK when there is a goal pose constraint. Removed unused `frame_id` initialisation. Transforms the goal pose for `CIRC`, `LIN` and `PTP` wrt. the planning frame. Transform the center point for `CIRC` wrt. the planning frame.

Rebased on #3519.

**TODO**
- [x] Fix CIRC
- [x] Fix LIN and PTP
- [ ] Add unit tests
- [ ] Update [moveit_tutorials](https://github.com/ros-planning/moveit_tutorials) doc for goals in cartesian space as well as interim/center point -> all frames are resolved with the start pose

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

---
**This post has been edited prior discussion with the maintainers**

### CODE REVIEW

**Comment by captain-yoshi** [comment]
The current unit test uses the prbt robot from [moveit_resources](https://github.com/ros-planning/moveit_resources/tree/melodic-devel/prbt_moveit_config). To demonstrate some of my fixes, I need one more fixed link between the robot base and the *prbt_link_1* that is different then the identity matrix.

I can't seem to add/modify links programatically with the robot model. Should I add an alternate _prbt_macro.xacro_ with another link in the moveit_resources ?

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_circ.cpp [hunk 1]
```diff
@@ -93,6 +93,23 @@ void TrajectoryGeneratorCIRC::extractMotionPlanInfo(const planning_scene::Planni
...
+    if (it == req.start_state.joint_state.name.cend())
+    {
+      std::ostringstream os;
+      os << "Could not find joint \"" << joint_name << "\" of group \"" << req.group_name
+         << "\" in start state of request";
+      throw CircJointMissingInStartState(os.str());
+    }
+    size_t index = it - req.start_state.joint_state.name.cbegin();
+    info.start_joint_position[joint_name] = req.start_state.joint_state.position[index];
+  }
```
Comment (rhaschke) [inline moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_circ.cpp:112]: This code block was removed in #3519. To which extend do you still need that?

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_circ.cpp [hunk 2]
```diff
@@ -142,54 +160,85 @@ void TrajectoryGeneratorCIRC::extractMotionPlanInfo(const planning_scene::Planni
...
-  assert(req.start_state.joint_state.name.size() == req.start_state.joint_state.position.size());
-  for (const auto& joint_name : robot_model_->getJointModelGroup(req.group_name)->getActiveJointModelNames())
-  {
-    auto it{ std::find(req.start_state.joint_state.name.cbegin(), req.start_state.joint_state.name.cend(), joint_name) };
-    if (it == req.start_state.joint_state.name.cend())
+    const auto link = robot_model_->getLinkModel(frame_id);
+    if (link)
     {
+      // check if robot link is rigidly connected to the root link
+      const auto parent_link = robot_model_->getRigidlyConnectedParentLinkModel(link);
```
Comment (rhaschke) [inline moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_circ.cpp:168]: There is also:
https://github.com/ros-planning/moveit/blob/167a62176b69a3afe102a2c9696aaf20225c52e4/moveit_core/robot_state/include/moveit/robot_state/robot_state.h#L1389-L1390

which allows to combine these two cases.

**Review by rhaschke — COMMENTED** [review]
Thanks for working on this. As you rely on #3519, could you please rebase onto that PR and further minimize the change set? There are a lot of code shifts, which distract from the actual contribution.

> The frame_id must be rigidly connected to the root link. There is no sense to use a frame that is not yet known for a goal pose constraint.

I don't agree with this. Of course, the frame needs to be known, but it could be _any_ known frame. For example, why shouldn't it be possible to specify the circular motion w.r.t. the current end-effector pose? Surely, this needs to be transformed into planning frame.

> I need one more fixed link between the robot base and the prbt_link_1. But I can't seem to add links programatically with the robot model.

What about adding a sub frame instead and using that one as frame_id?

I changed the status of that PR to draft as this is obviously still work-in-progress.

**Comment by captain-yoshi** [comment]
Will rebase and minimize the changes.

> I don't agree with this. Of course, the frame needs to be known, but it could be any known frame. For example, why shouldn't it be possible to specify the circular motion w.r.t. the current end-effector pose? Surely, this needs to be transformed into planning frame.

You are right. We should allow every frame_id (robot link, collision object/subframes) that is: 
- rigidly connected to the root link
- wrt. the _link_name_ of the constraint and everything up the chain that is attached to a fixed joint

Can someone plan something with a pure position constraint, e.g. the orientation could change, or is the orientation set to identity when missing ?

> What about adding a sub frame instead and using that one as frame_id ?

This would work, but there would be one test missing that checks explicitly if the frame is a link. Maybe I can simplify these checks. Nonetheless I will start testing with sub-frames.

**Comment by rhaschke** [comment]
> We should allow every frame_id that is ... rigidly connected to the root link.

There is no need to constrain to frames that are (rigidly) connected to the root link. 

> Can we plan with a pure position constraint?

Sure. Orientation of the eef is arbitrary in that case.

> There would be one test missing that checks explicitly if the frame is a link.

There is no need to test that explicitly. The planning code doesn't differ if the frame_id refers to a link or a sub frame.

**Comment by rhaschke** [comment]
> > Can we plan with a pure position constraint?
> 
> Sure. Orientation of the eef is arbitrary in that case.
> 
> >

You were probably asking that question in the context of the Pilz planner. To be honest, there I don't know.
My answer was for OMPL.

**Comment by captain-yoshi** [comment]
Here is my understanding of valid frames versus constraint link names:
image
 
Depending of the type of joint, there could be more valid frames, e.g for the link_name `Link TCP` one could use the `Link3/2` for frame_id and it would be valid if J3 was revolute. I don't think this is necessary...

And considering the case were orientation is not constrained, that means that a link_name with `Link TCP` and a frame_id of `Link TCP` would be correct, but a frame_id with `Bottle` or `Bottle/Cap` would not be valid because of the IK (only constraint in link_name position).

**Comment by captain-yoshi** [comment]
We can also just transform the goal pose wrt. the planning frame, without checking if the frame is valid (known in advanced). It would be up to the user to enter a valid _frame_id_.

**Comment by rhaschke** [comment]
I still don't get why you want to constrain possible frame_id's. The frame_id just defines the frame w.r.t. which the start, end, and center point of a CIRC motion are interpreted. As long as the frame is known (and somehow linked to the robot's TF tree), we can use the _current_ pose of that frame to transform those points into the planning frame. From there on, the CIRC path in space is fixed and well-defined w.r.t. the planning frame.

**Comment by captain-yoshi** [comment]
Sorry, I wrongfully though that we had to use the goal pose state for the goal pose constraint (which some frames are not known in advance) instead of the current pose which are known in advance.

**Review by rhaschke — COMMENTED** [review]
I merged #3519. Could you please rebase on master again? 
I shortly looked into your changes as well. As far as I understand, the main culprit is that the start pose is computed w.r.t. the robot's model frame (via FK) while the goal pose, computed via `getConstraintPose()`, is local w.r.t. to `frame_id` (which often/in the tests? coincides with the former).
It would be great, if you could add tests. Specifying the goal pose w.rt. to any frame != model frame should reveal the issue.

**Comment by captain-yoshi** [comment]
Rebased. Exactly, the tests use the planning frame as the _frame_id_. Will add tests tomorrow or this weekend.

**Comment by captain-yoshi** [comment]
Had a hard time finding that the `prbt_tcp` link was actually different for the 2 robot models: default and with the pg70 gripper.

The [test code](https://github.com/ros-planning/moveit/blob/master/moveit_planners/pilz_industrial_motion_planner/test/unittest_trajectory_generator_circ.cpp#L192-L193) for computing CIRC center point has the same problem, it does not transform the pose wrt. the frame_id. Can I use the same code (fixed in 846f6116dfda4427ff0779d3077c5b37f519847c) to compute the center point in the test or should I use a different method ? Obviously, if there is an error, the test will not be able to catch it.

Just have to fix one final error with my new test: `testutils::isGoalReached`. I suspect that it does not correctly transforms the goal pose wrt. the planning frame.

**Comment by rhaschke** [comment]
> Can I use the same code (fixed in [846f611](https://github.com/ros-planning/moveit/commit/846f6116dfda4427ff0779d3077c5b37f519847c)) to compute the center point in the test or should I use a different method?

I think it is fine using the same approach. Your main issue was that start and goal were computed w.r.t. different frames and this will be catched, right?
Is the PR ready for review from your point of view? I will have a look into it later this weekend.

**Comment by rhaschke** [comment]
@captain-yoshi, although I merged this PR already, please don't hesitate to add your unit tests.
I added some more fixes in #3523.
