### PR TITLE
OMPL logging that uses rosconsole

### LINKED ISSUE #719: OMPL Info and Debug logs are shown since latest update, even though verbose/debug mode is not specified
### Description
OMPL Info and Debug logs are shown since latest update, even though verbose/debug mode is not specified.

### Your environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04
* Binary build:  0.9.10

### Steps to reproduce
From package created with Setup Assistant, launch move_group.launch with arguments `debug` and `info` set to false.

### Expected behaviour
Not to see OMPL Debug or Info logs in the terminal.

### Actual behaviour
image

### Backtrace or Console output
https://gist.github.com/hansondon/229df6962bb55389cc72fcb2b2fa7832

### PR DESCRIPTION
**Pull request by zkingston**
### Description

Fixes #719. Adds a custom `ompl::msg::OutputHandler` that uses `rosconsole` to log OMPL messages at the appropriate logging level.

### Checklist
- [x] **Required**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)

### CODE REVIEW

File: moveit_planners/ompl/ompl_interface/src/ompl_planner_manager.cpp [hunk 1]
```diff
@@ -58,6 +60,51 @@ class OMPLPlannerManager : public planning_interface::PlannerManager
...
+          {
+          }
+
+          ~OutputHandler() override
+          {
+          }
+
+          void log(const std::string &text, ompl::msg::LogLevel level, const char *filename, int line) override
+          {
+              std::unique_lock<std::mutex> lock(lock_);
```
Comment (rhaschke) [inline moveit_planners/ompl/ompl_interface/src/ompl_planner_manager.cpp]: Do you really need locking? ROS_CONSOLE / the underlying logging uses locking as well.

File: moveit_planners/ompl/ompl_interface/src/ompl_planner_manager.cpp [hunk 2]
```diff
@@ -47,17 +47,58 @@
...
+
 #include <memory>
 
 namespace ompl_interface
 {
 using namespace moveit_planners_ompl;
 
+#define OMPL_ROS_LOG                                                                                                   \
+  {                                                                                                                    \
+    ROSCONSOLE_DEFINE_LOCATION(true, ::ros::console::levels::Debug, ROSCONSOLE_NAME_PREFIX ".ompl");                   \
```
Comment (zkingston) [inline moveit_planners/ompl/ompl_interface/src/ompl_planner_manager.cpp]: It looks like this should be:
```c++
#define OMPL_ROS_LOG(ros_level) \
 { \
   ROSCONSOLE_DEFINE_LOCATION(true, ros_level, ROSCONSOLE_NAME_PREFIX ".ompl"); \
...
```
Is that correct?

Comment (rhaschke) [reply moveit_planners/ompl/ompl_interface/src/ompl_planner_manager.cpp]: Well spotted. I pushed the fix. If you agree, I will do the final merge.

**Comment by zkingston** [comment]
Looks good to me, thanks for the help.
