### PR TITLE
chomp: fix potential calculation

### LINKED ISSUE #1650: This line should be `diff / clearance` as comment suggested?
https://github.com/ros-planning/moveit/blob/0ef84b85430a514fb9c095b8085954b582e2a38c/moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h#L97

### PR DESCRIPTION
**Pull request by rhaschke**
Fix #1650. The potential is a piecewise function as follows:

image

To have a smooth transition at zero, we need
```c++
double gradient_magnitude = diff / clearance;
```
as was stated in the comment.

### CODE REVIEW

File: moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h [hunk 1]
```diff
@@ -84,25 +84,21 @@ class ChompOptimizer
...
+      return 0.0;
     }
-    else if (d >= 0.0)
+    else if (d >= 0.0)  // transition phase, no collision yet
     {
       double diff = (d - clearence);
-      double gradient_magnitude = diff * clearence;  // (diff / clearance)
-      potential = 0.5 * gradient_magnitude * diff;
+      double gradient_magnitude = diff / clearence;
+      return 0.5 * gradient_magnitude * diff;  // 0.5 * (d - clearance)^2 / clearance
```
Comment (bmagyar) [inline moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h]: It may be worth referencing the formula here, I don't remember by heart if the CHOMP papers have it.

File: moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h [hunk 2]
```diff
@@ -84,25 +84,21 @@ class ChompOptimizer
...
-      potential = 0.0;
+      return 0.0;
     }
-    else if (d >= 0.0)
+    else if (d >= 0.0)  // transition phase, no collision yet
     {
       double diff = (d - clearence);
-      double gradient_magnitude = diff * clearence;  // (diff / clearance)
-      potential = 0.5 * gradient_magnitude * diff;
+      double gradient_magnitude = diff / clearence;
```
Comment (bmagyar) [inline moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h]: I'd use consts here as much as possible but it's really nitpicking so please feel free to resolve & ignore if you don't want to make those changes

File: moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h (hunk 1 above)
Comment (rhaschke) [reply moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h]: Which formula do you want to reference? I already added the formula as a comment.

File: moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h (hunk 2 above)
Comment (rhaschke) [reply moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h]: Would be fine with me. Next time, please propose such a small change directly in github. This allows me to accept it and proceed.

File: moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h [hunk 3]
```diff
@@ -84,25 +84,21 @@ class ChompOptimizer
...
-    if (d >= clearence)
+    if (d >= clearence)  // everything is fine
     {
-      potential = 0.0;
+      return 0.0;
     }
-    else if (d >= 0.0)
+    else if (d >= 0.0)  // transition phase, no collision yet
     {
       double diff = (d - clearence);
```
Comment (rhaschke) [inline moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h]:
```suggestion
      const double diff = (d - clearence);
```

File: moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h (hunk 2 above)
Comment (rhaschke) [inline moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h]:
```suggestion
      const double gradient_magnitude = diff / clearence;
```

File: moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h (hunk 1 above)
Comment (bmagyar) [reply moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h]: I saw the comment. I meant if there's a good reference an interested reader could go to.

Comment (rhaschke) [reply moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h]: Ah. Ok. No idea, where to find such a reference.
I just verified the formula using my mathematical common sense :wink:

File: moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h (hunk 2 above)
Comment (rhaschke) [reply moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h]: I think, this is ready to merge then. @bmagyar, can you approve?

Comment (bmagyar) [reply moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.h]: Righty-ho captain!
