### PR TITLE
Fix pilz planners to consider and plan Cartesian motions w.r.t. subframes

### LINKED ISSUE #3517: Pilz LIN motions with subframes are not linear in the motion the subframe takes
### Description

When planning a LIN motion using a subframe as the link_name in constraints, the motion taken by the end link is linear, rather than the motion taken by the subframe (which is often nonlinear)

### Your environment
* ROS Distro: Noetic
* OS Version: e.g. Ubuntu 20.04 (focal)
* Source or Binary build? Source (noetic-devel) or Docker Image (moveit/moveit:noetic-release)

### Steps to reproduce
The problem can be reproduced as follows:
   - Add the `default_planner_request_adapters/ResolveConstraintFrames` adapter to `pilz_industrial_motion_planner.yaml`
   - Load a robot
   - Attach a collision object to the robot
   - Add a subframe to the collision object
   - Build a GetMotionSequence request with the following properties:
      - First point as the current pose
      - Second point with a position constraint and orientation constraint using the subframe as the link_name
         - I used a 0.1m offset along x and -90 degree rotation around x relative to the subframe
      - Planner: pilz_industrial_motion_planner, LIN
   - Call the PlanMotionSequence service 

### Expected behaviour
The motion should move the subframe from the start pose to the end pose with the subframe taking a linear path. I managed to emulate the desired behaviour by planning a PTP path between the same start and end goal, inserting 100 extra samples of the linear path as waypoints:

https://github.com/ros-planning/moveit/assets/86778266/ded26586-3fc1-4e5a-a47e-aa4bb746c856

### Actual behaviour
The motion moves the subframe from the start to the end pose, but the motion the subframe takes is nonlinear. Instead, the motion that takes end link to the poses needed to put the subframe in the right start and end poses is linear instead:

https://github.com/ros-planning/moveit/assets/86778266/769305cf-679a-4e3e-9567-36cc79597e28

### Backtrace or Console output

Motion plan constraints for the goal point as sent to PlanMotionSequence:

```
[18:15:29.721657] [/fake/motion_server]: name: 
joint_constraints[]
position_constraints[]
  position_constraints[0]: 
    header: 
      seq: 0
      stamp: 0.000000000
      frame_id: world
    link_name: tb_1_1/disc_tip
    target_point_offset: 
      x: 0
      y: 0
      z: 0
    constraint_region: 
      primitives[]
        primitives[0]: 
                type: 2
          dimensions[]
      primitive_poses[]
        primitive_poses[0]: 
                position: 
            x: 0.463583
            y: 0.000855646
            z: 0.394315
          orientation: 
            x: 0.707088
            y: 0.00515615
            z: 0.000812115
            w: 0.707106
      meshes[]
      mesh_poses[]
    weight: 1
orientation_constraints[]
  orientation_constraints[0]: 
    header: 
      seq: 0
      stamp: 0.000000000
      frame_id: world
    orientation: 
      x: 0.707088
      y: 0.00515615
      z: 0.000812115
      w: 0.707106
    link_name: tb_1_1/disc_tip
    absolute_x_axis_tolerance: 0
    absolute_y_axis_tolerance: 0
    absolute_z_axis_tolerance: 0
    parameterization: 0
    weight: 1
visibility_constraints[]
```

Motion plan constraints for the goal point as received by LIN:

```
[18:15:29.979323] [/fake/move_group]: name: 
joint_constraints[]
position_constraints[]
  position_constraints[0]: 
    header: 
      seq: 0
      stamp: 0.000000000
      frame_id: world
    link_name: axia80_mate
    target_point_offset: 
      x: -0.160755
      y: -1.16121e-05
      z: 0.120096
    constraint_region: 
      primitives[]
        primitives[0]: 
                type: 2
          dimensions[]
      primitive_poses[]
        primitive_poses[0]: 
                position: 
            x: 0.463583
            y: 0.000855646
            z: 0.394315
          orientation: 
            x: 0.707088
            y: 0.00515615
            z: 0.000812115
            w: 0.707106
      meshes[]
      mesh_poses[]
    weight: 1
orientation_constraints[]
  orientation_constraints[0]: 
    header: 
      seq: 0
      stamp: 0.000000000
      frame_id: world
    orientation: 
      x: 0.49578
      y: 0.503044
      z: 0.50422
      w: 0.496901
    link_name: axia80_mate
    absolute_x_axis_tolerance: 0
    absolute_y_axis_tolerance: 0
    absolute_z_axis_tolerance: 0
    parameterization: 0
    weight: 1
visibility_constraints[]
```

I tried turning off the `default_planner_request_adapters/ResolveConstraintFrames` adapter, which (not unexpectedly) causes the two plans to agree. I believed that some parts of MoveIt are subframe aware e.g. `RobotState::getFrameTransform()`, so I thought the MoveIt / IK calls might be able to handle the tranforms between the subframe and end link behind-the-scenes, however, this leads to IK related failures:

```
[18:23:08.760746] [/fake/move_group]: This is the line that fails using a subframe as the target
[18:23:08.760860] [/fake/move_group]: File: ${WORKSPACE}/src/moveit/moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp, Line: 209
[18:23:08.761253] [/fake/move_group]: No IK solver available for link: "tb_1_1/disc_tip"
[18:23:08.761532] [/fake/move_group]: Planner threw an exception (error code: -31): Could not solve request
```
I'm wondering if the `default_planner_request_adapters/ResolveConstraintFrames` adapter should pass the entire frame of the target point relative to the end link. That way, LIN can build a `KDF::Line` subframe start and goal, sample a bunch of poses transformed into the end link frame, then pass that end link path to the IK solver?

Alternatively, the tranformation between poses in the path could be done in the same method that IK is called over the path e.g. for each pose, perform IK if the link is not a subframe, else transform and perform IK (to avoid resampling the path twice and to ensure the sample rates match up)
 
Then again, if the intention is for that adapter to hide any subframe details from the planner, this seems like it would defeat the purpose. I don't see any way of allowing LIN to achieve this without requiring subframe knowledge though, since it's all points along the path that need to satify a certain subframe property, and the points generated in the middle are an implementation detail of the planner which a pre-processer couldn't account for  (also this adapter already seems to pass some information through using the target_point_offset field)

Any ideas would be much appreciated!

### PR DESCRIPTION
**Pull request by rr-tom-noble**
### Description

Fixes #3517 by allowing pilz to use subframes in goal constraints.

Updates `computePoseIK()` to build a `RobotState` from the `PlanningScene` rather than the `RobotModel`, so that subframes are taken into account. Also adds some error handling logic around calls to this function as, currently, if the passed `link_name` does not exist, the `start_pose` is set to the identity pose, which leads to a less intuitive IK solver error later on.

This also means the collision checking in the pilz `computePoseIK()` method is now attached collision object aware.

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

File: moveit_planners/pilz_industrial_motion_planner/src/command_list_manager.cpp [hunk 1]
```diff
@@ -239,7 +239,8 @@ CommandListManager::solveSequenceItems(const planning_scene::PlanningSceneConstP
     if (res.error_code_.val != res.error_code_.SUCCESS)
     {
       std::ostringstream os;
-      os << "Could not solve request\n---\n" << req << "\n---\n";
+      // os << "Could not solve request\n---\n" << req << "\n---\n";
```
Comment (rhaschke) [inline moveit_planners/pilz_industrial_motion_planner/src/command_list_manager.cpp:242]: Drop this line.
```suggestion
```

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp [hunk 2]
```diff
@@ -67,7 +75,8 @@ bool pilz_industrial_motion_planner::computePoseIK(const planning_scene::Plannin
     return false;
   }
 
-  robot_state::RobotState rstate(robot_model);
+  moveit::core::RobotState rstate = scene->getCurrentState();
+
```
Comment (rhaschke) [inline moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp:79]: Why this? Next line, you reset joint values to defaults.

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp [hunk 3]
```diff
@@ -53,11 +53,19 @@ bool pilz_industrial_motion_planner::computePoseIK(const planning_scene::Plannin
...
+  std::string ik_link_name = link_name;
+  Eigen::Isometry3d ik_link_pose = pose;
+  if (jmg->canSetStateFromIK(link_name))
   {
-    ROS_ERROR_STREAM("No valid IK solver exists for " << link_name << " in planning group " << group_name);
-    return false;
+    /// Transforms the goal into a link goal if link_name is a subframe
+    if (scene->knowsFrameTransform(link_name)) {
+      ik_link_name = jmg->getSolverInstance()->getTipFrame();
+      ik_link_pose = pose * scene->getFrameTransform(link_name).inverse() * scene->getFrameTransform(ik_link_name);
```
Comment (rhaschke) [inline moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp:64]: This should check that the transform between `link_name` and `ik_link_name` is _fixed_.

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp [hunk 4]
```diff
@@ -203,12 +203,12 @@ void TrajectoryGenerator::checkCartesianGoalConstraint(const moveit_msgs::Constr
...
-    std::ostringstream os;
-    os << "No IK solver available for link: \"" << pos_constraint.link_name << "\"";
-    throw NoIKSolverAvailable(os.str());
-  }
+  // if (!robot_model_->getJointModelGroup(group_name)->canSetStateFromIK(pos_constraint.link_name))
+  // {
+  //   std::ostringstream os;
+  //   os << "No IK solver available for link: \"" << pos_constraint.link_name << "\"";
+  //   throw NoIKSolverAvailable(os.str());
+  // }
```
Comment (rhaschke) [inline moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp:211]: If not needed anymore: remove completely. Leave a comment here, why it's not needed anymore.
I guess it is redundant to similar checks elsewhere?

But: Instead of doing the error checking and reporting frequently in downstream trajectory generators, why not do it once here?

**Review by rhaschke — COMMENTED** [review]
Generally, I think the approach is correct. In order to yield interpolation w.r.t. the subframe, the frame needs to be resolved in the Pilz planner and not only in `setFromIK`.

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp (hunk 2 above)
Comment (rr-tom-noble) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp:79]: The only reason for using a robot state from the scene is that it comes with the attached objects / subframes, which the previous `robot_state::RobotState rstate(robot_model);` did not. No reason for choosing the current state in particular. If there's a neater way doing this I'm happy to change it

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp (hunk 3 above)
Comment (rr-tom-noble) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp:64]: Are there methods available in MoveIt I can use to check that?

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp (hunk 2 above)
Comment (rhaschke) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp:79]: Given that this state is used for IK, I suggest to drop `setToDefaultValues()`.

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp [hunk 5]
```diff
@@ -111,12 +120,12 @@ bool pilz_industrial_motion_planner::computePoseIK(const planning_scene::Plannin
                        timeout);
 }
 
-bool pilz_industrial_motion_planner::computeLinkFK(const moveit::core::RobotModelConstPtr& robot_model,
+bool pilz_industrial_motion_planner::computeLinkFK(const planning_scene::PlanningSceneConstPtr& scene,
```
Comment (rhaschke) [inline moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp:123]: Do you really need the full PS or is the RobotState enough? If so, use the latter only.

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp (hunk 4 above)
Comment (rr-tom-noble) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp:211]: Will double check that this is redundant. Do you think it'd make sense to move the transformation into a tip goal here too?

**Comment by rr-tom-noble** [comment]
Simple sanity check of the LIN output:
https://github.com/ros-planning/moveit/assets/86778266/4c341090-64c1-4856-96a2-662006716dbf

Will do the same for CIRC as I believe a decent portion of the code is shared

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp (hunk 5 above)
Comment (rr-tom-noble) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp:119]: `RobotState` should be enough. Will do that now. I wonder if it's also worth removing [this](https://github.com/ros-planning/moveit/blob/9f8f6bbe0627619bd79928edd5f4d21047690255/moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp#L134C3-L134C31) line, since we immediately set the joint values afterwards

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp (hunk 3 above)
Comment (rhaschke) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp:64]: There is `RobotState::getRigidlyConnectedParentLinkModel` which also directly provides the relative transform:
https://github.com/ros-planning/moveit/blob/984a0ea2a00b4190cad9e08ea0d764c19dbf9975/moveit_core/robot_state/include/moveit/robot_state/robot_state.h#L1388-L1390

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp (hunk 2 above)
Comment (rr-tom-noble) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp]: Done :+1:

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp (hunk 3 above)
Comment (rr-tom-noble) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp:64]: I just noticed that the logic on [this](https://github.com/ros-planning/moveit/blob/c7c1b5e83661327a165196d31bf86b66d6f650c9/moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp#L59) line should be negated for catching subframes, meaning the fixes to the link name validation logic and `computePoseIK()` seem to be sufficient for planning with subframes: `setFromIK()` already handles the transformation under the hood.

Comment (rr-tom-noble) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp]: Done :+1:

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp (hunk 4 above)
Comment (rr-tom-noble) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp:211]: > Do you think it'd make sense to move the transformation into a tip goal here too?

Scratch that part given the transformation is no longer necessary (see reply from above comment)

@rhaschke What would be the easiest way of turning this check into one that can detect subframes? In other places, I've been using `RobotState::knowsFrameTransform()`. 

The method calls are:

`TrajectoryGenerator::generate() -> TrajectoryGenerator::validateRequest() -> TrajectoryGenerator::checkGoalConstraints() -> TrajectoryGenerator::checkCartesianGoalConstraint()`

The first of those methods has access to a planning scene, though I'm unsure if there's a cleaner way than passing a state through the method calls (especially since the state itself is arbitrary, it's just the access to the subframes we're interested in)

Comment (rhaschke) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp:211]: From my understanding, the check (for existence of the IK (sub)frame and it's usability for IK) didn't fail.
In contrast to `RobotState::knowsFrameTransform()`, `canSetStateFromIK()` should also verify that the IK frame is rigidly connected to the IK solver's tip frame (so exactly what you need).

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp (hunk 5 above)
Comment (rr-tom-noble) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp]: Done :+1:

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp (hunk 4 above)
Comment (rr-tom-noble) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp:211]: I do get the same error as before uncommenting this when planning with a subframe:

```
[10:15:49.016004] [/fake/move_group]: No IK solver available for link: "tb_1_1/disc_tip"
[10:15:49.016126] [/fake/move_group]: Planner threw an exception (error code: -31): Could not solve request

[10:15:49.017372] [/fake/motion_server]: Failed to plan sequence motion foo. Error code: NO_IK_SOLUTION. If problem persists, check toolbit config.
```

I think the issue the issue is that `JointModelGroup` has no notion of subframes and only checks for links in `canSetFromIK`, whereas `RobotState` knows about both and `setFromIK` is designed for that possibility.

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp [hunk 6]
```diff
@@ -53,12 +53,9 @@ bool pilz_industrial_motion_planner::computePoseIK(const planning_scene::Plannin
...
   }
-
-  if (!robot_model->getJointModelGroup(group_name)->canSetStateFromIK(link_name))
-  {
-    ROS_ERROR_STREAM("No valid IK solver exists for " << link_name << " in planning group " << group_name);
-    return false;
-  }
+  const moveit::core::JointModelGroup* jmg = robot_model->getJointModelGroup(group_name);
+  moveit::core::RobotState rstate = scene->getCurrentState();
+  rstate.setVariablePositions(seed);
```
Comment (rhaschke) [inline moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp:58]: To minimize changes, I suggest to keep that block below the next if-block.

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp [hunk 7]
```diff
@@ -111,28 +102,24 @@ bool pilz_industrial_motion_planner::computePoseIK(const planning_scene::Plannin
...
+  if (!robot_state.knowsFrameTransform(link_name))
   {
     ROS_ERROR_STREAM("The target link " << link_name << " is not known by robot.");
     return false;
   }
 
   // set the joint positions
-  rstate.setToDefaultValues();
-  rstate.setVariablePositions(joint_state);
+  robot_state.setToDefaultValues();
```
Comment (rhaschke) [inline moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp:117]: I think this line should be dropped.
```suggestion
```

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_circ.cpp [hunk 8]
```diff
@@ -125,7 +126,12 @@ void TrajectoryGeneratorCIRC::extractMotionPlanInfo(const planning_scene::Planni
       info.goal_joint_position[joint_item.joint_name] = joint_item.position;
     }
 
-    computeLinkFK(robot_model_, info.link_name, info.goal_joint_position, info.goal_pose);
+    if (!computeLinkFK(robot_state, info.link_name, info.goal_joint_position, info.goal_pose))
+    {
+      std::ostringstream os;
+      os << "Failed to compute forward kinematics for link: " << info.link_name << " of goal joints";
+      throw CircForwardForGoalIncalculable(os.str());
+    }
```
Comment (rhaschke) [inline moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_circ.cpp:134]: Instead of duplicating this code in all calls to `computeLinkFK()`, why don't you throw directly from within this function?

**Review by rhaschke — COMMENTED** [review]
More feedback below.

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp (hunk 6 above)
Comment (rr-tom-noble) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_functions.cpp]: Done :+1:

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_circ.cpp (hunk 8 above)
Comment (rr-tom-noble) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_circ.cpp]: Done :+1:

**Comment by rr-tom-noble** [comment]
We're currently looking into an issue using this for our use case, which is as follows:
  - We plan to rotate a separate planning group (the current state of that group is unrotated)
  - We pass the expected rotation of that other planning group as part of the start state in the sequence request
  - The changes to use a robot state from `getCurrentState()` now takes collision objects into account (desired)
  - However, (I think) this also takes a collision object of the unrotated other planning group into account (rather than the rotated start state version)
  - This causes a collision (which is not an issue, as we expect the other planning group to have already rotated by the time we plan, hence setting the start state as such)

@rr-mark is also looking into this issue

**Comment by rr-mark** [comment]
> @rr-mark is also looking into this issue

It looks like
 - constructing the robot state from the robot model has the correct joint states, but no attached collision objects.
 - constructing the robot state from the planning scene has the attached collision objects, but the joint states are the current state, rather than the planning context.

I'm currently trying to rationalise the two; it would be good to get help from someone who know more about what is supposed to happen here.

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_lin.cpp [hunk 9]
```diff
@@ -134,9 +133,7 @@ void TrajectoryGeneratorLIN::extractMotionPlanInfo(const planning_scene::Plannin
     info.start_joint_position[joint_name] = req.start_state.joint_state.position[index];
   }
```
Comment (rr-mark) [inline moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_lin.cpp:134]:
```suggestion
for (unsigned i=0; i<req.start_state.joint_state.name.size(); ++i) {
    info.start_joint_position[req.start_state.joint_state.name[i]] = req.start_state.joint_state.position[i];
  }
  for (const auto& joint_name : robot_model_->getJointModelGroup(req.group_name)->getActiveJointModelNames())
  {
    if (info.start_joint_position.count(joint_name) == 0)
    {
      std::ostringstream os;
      os << "Could not find joint \"" << joint_name << "\" of group \"" << req.group_name
         << "\" in start state of request";
      throw LinJointMissingInStartState(os.str());
    }
  }
```

Comment (rr-mark) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator_lin.cpp:134]: ^ (replacing everything inside that `{}` (I can't work out how to do multi-line suggestions))

looks like it correctly updates all the joint states, including those not in the current joint group.

**Comment by rhaschke** [comment]
I'm not sure what (remaining?) problem you are referring to in https://github.com/ros-planning/moveit/pull/3519#issuecomment-1788707626 and https://github.com/ros-planning/moveit/pull/3519#issuecomment-1788737312.
In general, a planner should use the current state of the PS (`PlanningScene::getCurrentState()`) for planning and this state should comprise all joint values. However, this state might differ from the real current robot state.

That `computePoseIK()` wasn't using that state, but a newly created one, was definitely a design bug.

**Review by rhaschke — APPROVED** [review]
I think this looks good now.

**Comment by rr-mark** [comment]
> I'm not sure what (remaining?) problem you are referring to in [#3519 (comment)](https://github.com/ros-planning/moveit/pull/3519#issuecomment-1788707626) and [#3519 (comment)](https://github.com/ros-planning/moveit/pull/3519#issuecomment-1788737312). In general, a planner should use the current state of the PS (`PlanningScene::getCurrentState()`) for planning and this state should comprise all joint values. However, this state might differ from the real current robot state.
> 
> That `computePoseIK()` wasn't using that state, but a newly created one, was definitely a design bug.

Ah, sorry, I'll try to clarify:

We have six joints (a-f) in the active joint model, one joint (z) in another joint model.

The problem I was seeing was that the robot state constructed in `computePoseIK` from `scene->getCurrentState()` had `z=0`, and this was not being updated by `seed`, as `seed` is constructed in `TrajectoryGeneratorLIN::extractMotionPlanInfo` to only contain joints in `getActiveJointModelNames`.

The push I have just made updates `seed` so it contains all joints, not just those in `getActiveJointModelNames`.

If I understand your message correctly, the fact that `getCurrentState` has `z=0` is a bug? And `seed` should not need the joints outside of `getActiveJointModelNames`? Would you know where I should be looking to find why `getCurrentState` is returning the wrong robot state?

**Review by rhaschke — CHANGES_REQUESTED** [review]
Please revert your changes. During planning, only joints of the planning group should be modified. All other joints should be adapted _once_ at the beginning.
The PlanningScene passed to the planning context reflects the current robot state (of the real robot). Any modifications to that state can be passed in the request's start_state.
I can propose a solution in a few minutes.

**Comment by rr-mark** [comment]
I am now seeing crashes when I plan motions. I'll take a look into them now.

**Comment by rhaschke** [comment]
Sorry, I didn't run the tests anymore - it was too late.

**Comment by rr-mark** [comment]
No worries

**Comment by rr-mark** [comment]
It looks like it's the call to `plan_info.start_scene->getCurrentState()` which is failing. `start_scene` is default constructed and never touched again. What should I change to give this the relevant information?

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp [hunk 10]
```diff
@@ -352,10 +356,26 @@ bool TrajectoryGenerator::generate(const planning_scene::PlanningSceneConstPtr&
...
 
-  moveit::core::RobotState start_state(scene->getCurrentState());
-  moveit::core::robotStateMsgToRobotState(req.start_state, start_state, true);
-  setSuccessResponse(start_state, req.group_name, joint_trajectory, planning_begin, res);
+  setSuccessResponse(plan_info.start_scene->getCurrentState(), req.group_name, joint_trajectory, planning_begin, res);
   return true;
 }
 
+TrajectoryGenerator::MotionPlanInfo::MotionPlanInfo(const planning_scene::PlanningSceneConstPtr& scene,
+                                                    const planning_interface::MotionPlanRequest& req)
```
Comment (rr-mark) [inline moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp:364]:
```suggestion
                                                    const planning_interface::MotionPlanRequest& req) : start_scene(scene)
```

Comment (rhaschke) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp:364]: > With this change I'm still getting z=0, rather than its value in the motion plan request.

That's the wrong start_scene. I will push a commit in a minute - if tests succeed locally.

> Are there any existing tests which use more than one joint model group?

Not sure. You could use the PR2 robot (having two arms), which is part of moveit_resources. Alternatively, use the Panda, which has a separate group for the hand and its finger joint.

Comment (rr-mark) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp:364]: Am I right in thinking your intent was to generate `start_scene` from `start_state` and `start_joint_positions`, and then pass `start_scene` rather than `scene` to `extractMotionPlanInfo`?

Comment (rhaschke) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp:364]: Exactly. I pushed a fixup for the missing initialization of `start_scene`. But there are still failing tests locally...

File: moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp [hunk 11]
```diff
@@ -326,7 +330,7 @@ bool TrajectoryGenerator::generate(const planning_scene::PlanningSceneConstPtr&
     return false;
   }
 
-  MotionPlanInfo plan_info;
+  MotionPlanInfo plan_info(scene, req);
   try
   {
     extractMotionPlanInfo(scene, req, plan_info);
```
Comment (rr-mark) [inline moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp:336]:
```suggestion
    extractMotionPlanInfo(plan_info.start_scene, req, plan_info);
```

Comment (rr-mark) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp:336]: This fixes the `z=0` problems I'm seeing.

Comment (rr-mark) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp:336]: Unsure if this change should also be made to `plan` on line 349?

Comment (rhaschke) [reply moveit_planners/pilz_industrial_motion_planner/src/trajectory_generator.cpp]: Yes, definitely!

**Review by rhaschke — APPROVED** [review]

**Comment by rr-mark** [comment]
Your changes work on my end, thank you for your time.

**Comment by rr-mark** [comment]
We're seeing a couple of issues with this PR:

 - Planning LIN paths is now much slower, as attached collision objects are now being considered in the collision checking (since they are now part of the robot state, where they weren't previously). https://github.com/ros-planning/moveit/pull/3518 helps a lot, but the net effect is still a slowdown.
 - Collisions along the path are now reported as IK failures, and nothing is published to `display_contacts`. This makes it harder to turn the output into a user-friendly error message.

Is all the extra collision checking working as intended? Or is this redundant with other collision checking after the path has been generated?

**Comment by rhaschke** [comment]
You are right, collision checking is performed twice: (i) during path generation and (ii) as a final trajectory validation step.
As the Pilz planner is not actually planning around obstacles, but simply generating a trajectory, we can skip the collision checking during planning. I will add a corresponding commit.

**Comment by rhaschke** [comment]
Actually, collision checking in `generateJointTrajectory()` is optional and [disabled by default](https://github.com/rr-tom-noble/moveit/blob/ff4f00038d479a361354e6396029b378a91747b8/moveit_planners/pilz_industrial_motion_planner/include/pilz_industrial_motion_planner/trajectory_functions.h#L134), particularly for all trajectory generators.  The only source that was using collision checking was [`blend()`](https://github.com/ros-planning/moveit/pull/3519/commits/eda07abdd36f9ff124f7445ab9b7abfa2a04b86a).

Can you please verify that the behavior is as intended now?

**Comment by rr-mark** [comment]
Yes, it looks good now; collisions along the path are reported as they were before this PR.

Thanks again.

**Comment by rhaschke** [comment]
Thanks for iterating on this.

**Comment by rhaschke** [comment]
While this PR seems to fix ignored modified start states in unrelated JMGs, the original issue is not yet solved, is it?

> When planning a LIN/CIRC motion using a subframe as the link_name in constraints, the motion is linear w.r.t. the end-effector _link_, rather than the _subframe_.

I think this can only be resolved by explicitly interpolating between the actual subframe's start and goal pose (i.e. not first back-projecting to the associated robot link) and considering the offset when computing the IK instead. I implemented this for the CartesianInterpolator in #3197. #2890, authored by you guys, should be reverted to a large extent in order to maintain the _original_ goal pose.

**Comment by rr-tom-noble** [comment]
> While this PR seems to fix ignored modified start states in unrelated JMGs, the original issue is not yet solved, is it?
> 
> > When planning a LIN/CIRC motion using a subframe as the link_name in constraints, the motion is linear w.r.t. the end-effector _link_, rather than the _subframe_.
> 
> I think this can only be resolved by explicitly interpolating between the actual subframe's start and goal pose (i.e. not first back-projecting to the associated robot link) and considering the offset when computing the IK instead. I implemented this for the CartesianInterpolator in #3197. #2890, authored by you guys, should be reverted to a large extent in order to maintain the _original_ goal pose.
> 
> Unfortunately, the unit tests don't cover those cases yet - they only consider the final goal pose, but don't check the path in between.

Hi, and thanks for the feedback and help with this PR.

I think the code does work as intended as passing in the subframe as the link_name and removing the default_planner_request_adapters/ResolveConstraintFrames adapter causes the target point offset to be [0. 0. 0].  The start and goal points _are_ for the subframe, and it's those points we use KDL to build the LIN motion for. It's only when we're sampling points along that path and performing IK that the points are back projected to a robot link (within the robot_state->setFromIK()) call I believe.

I do wonder if this makes the point of target_offset_point a little redundant, so I don't mind those changes being reverted. Maybe still useful if you _did_ want to plan using an offset from the subframe itself?

Let me know if you agree with the above

**Comment by rhaschke** [comment]
Sure, if you remove the ResolveConstraintFrames adapter, the target_point_offset becomes zero. However, I was complaining about the case when this offset is non-zero. See #3523 for the fix. Now it works with both ResolveConstraintFrames enabled or disabled.
