### PR TITLE
[planning_interface] Release Python GIL for C++ calls

### LINKED ISSUE #1580: Python GIL not released before entering the C++ library
### Description
Python GIL not released before entering the C++ library. The effect is that all rospy subscribers, publishers, transform listeners etc. are not updated. Effectively all communications with that python node are not possible anymore.

This issue was raised a few years back in this issue: https://github.com/ros-planning/moveit_commander/issues/28

### Your environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04
* Source or Binary build: The normal debian release
```
moveit_version 
0.9.17-Alpha
```

### Steps to reproduce
Execute a plan with moveit_commander that takes multiple seconds.

### Expected behaviour
A subscriber should be able to receive messages from other ros nodes while the plan is executing.

### Actual behaviour
The GIL is locked an the node is not able to execute any python code at all while the plan is executing.

### PR DESCRIPTION
**Pull request by gleichdick**
### Description

Fixes #1580. (C)Python has a Global Interpreter Lock (GIL) which should be released when doing long-lasting C++ calls.

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by gleichdick** [comment]
Good point, I reduced the usage of the GILReleaser to the following functions:
 - MoveGroupInterface::execute()
 - MoveGroupInterface::move()
 - MoveGroupInterface::plan()
 - MoveGroupInterface::computeCartesianPath()
 - MoveGroupInterfaceWrapper::retimeTrajectory()
 - RobotInterfacePython::ensureCurrentState()

File: moveit_ros/planning_interface/py_bindings_tools/include/moveit/py_bindings_tools/gil_releaser.h [hunk 1]
```diff
@@ -0,0 +1,109 @@
+/*********************************************************************
+ * Software License Agreement (BSD License)
+ *
+ *  Copyright (c) 2020, Willow Garage, Inc.
```
Comment (v4hn) [inline moveit_ros/planning_interface/py_bindings_tools/include/moveit/py_bindings_tools/gil_releaser.h]: please add your name/ organization.

File: moveit_ros/planning_interface/py_bindings_tools/include/moveit/py_bindings_tools/gil_releaser.h [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+ *  modification, are permitted provided that the following conditions
+ *  are met:
+ *
+ *   * Redistributions of source code must retain the above copyright
+ *     notice, this list of conditions and the following disclaimer.
+ *   * Redistributions in binary form must reproduce the above
+ *     copyright notice, this list of conditions and the following
+ *     disclaimer in the documentation and/or other materials provided
+ *     with the distribution.
+ *   * Neither the name of Willow Garage nor the names of its
```
Comment (v4hn) [inline moveit_ros/planning_interface/py_bindings_tools/include/moveit/py_bindings_tools/gil_releaser.h]: see above.

File: moveit_ros/planning_interface/py_bindings_tools/include/moveit/py_bindings_tools/gil_releaser.h (hunk 1 above)
Comment (gleichdick) [reply moveit_ros/planning_interface/py_bindings_tools/include/moveit/py_bindings_tools/gil_releaser.h]: Done
