### PR TITLE
[perception] fix mesh_filter test

### LINKED ISSUE #1109: Correctly fix moveit_ros_perception's mesh filter
Since #982, unit tests for `moveit_ros_perception` are disabled, [as the mesh_filter_test fails](https://travis-ci.org/ros-planning/moveit/jobs/403081276).
As the test passes on my side with an nvidia OpenGL setup, the issues seems to be related to Mesa OpenGL. 
* Either there is a (newly introduced) bug in Mesa OpenGL - this test used to pass and we didn't change it for ages.
* Or the way to use the API has changed somewhere in between.

Somebody with experience in offscreen OpenGL rendering should have a look at this.
https://github.com/ros-planning/moveit/tree/kinetic-devel/moveit_ros/perception/mesh_filter

Unfortunately, due to a typo in cmake files (fixed in #954), the mesh filter wasn't built for quite a while.

### PR DESCRIPTION
**Pull request by gleichdick**
### Description

The mesh_filter test was disabled a long time ago. The test passes when relaxing the acceptance region to 1e-6.

Closes #1109 

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by gleichdick** [comment]
Yes, the output of the failing testcase was
```
[  FAILED  ] ushort_test/MeshFilterTestUnsignedShort.unsigned_short/10, where GetParam() = 5 (155 ms)
[ RUN      ] ushort_test/MeshFilterTestUnsignedShort.unsigned_short/11
/home/user/moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234: Failure
      Expected: filtered_depth[idx]
      Which is: 0.67399973
To be equal to: gt_depth[idx]
      Which is: 0.67400002
```
It passes with `1e-6` on my KVM bionic virtual machine

**Comment by rhaschke** [comment]
Dear @gleichdick, I would prefer to merge the test fixup separately from subsequent clang-tidy fixes.
Could you please revert the latter ones?  I will prepare a thorough clang-tidy fix.

File: moveit_ros/perception/mesh_filter/src/stereo_camera_model.cpp [hunk 1]
```diff
@@ -109,7 +109,7 @@ void mesh_filter::StereoCameraModel::Parameters::setFilterParameters(GLRenderer&
 }
 
 // NOLINTNEXTLINE(readability-identifier-naming)
```
Comment (v4hn) [inline moveit_ros/perception/mesh_filter/src/stereo_camera_model.cpp]: is the `NOLINTNEXTLINE` related?
