### PR TITLE
Fix logic in PlanningScene::clearDiffs() for multiple CollisionDetectors

### LINKED ISSUE #2485: Segfault from the PlanningScene after allocating for Bullet collision detection
Attempting to allocate for Bullet collision detection like this:

```
planning_scene_monitor_->getPlanningScene()->setActiveCollisionDetector(collision_detection::CollisionDetectorAllocatorBullet::create());
```

or like this:

`
  {
     planning_scene_monitor::LockedPlanningSceneRW ls(planning_scene_monitor_);
      ls->setActiveCollisionDetector(collision_detection::CollisionDetectorAllocatorBullet::create());
  }
`
Causes a seg fault. Per gdb:

```
[Switching to Thread 0x7fff86ffb700 (LWP 25923)]
0x00007ffff20a1b9b in planning_scene::PlanningScene::clearDiffs() ()
   from /home/andyz/ws_al/devel/lib/libmoveit_planning_scene.so.1.1.1

```

### PR DESCRIPTION
**Pull request by AndyZe**
Fix a bug for the case when `it.second->parent_` is null (i.e. if the current Collision Detector is the parent or the only one).

Provide better Doxygen comments for `clearDiffs()`

This seems like a pretty deep bug. I guess it wasn't found previously because nobody is using >1 collision detection algorithm.

### CODE REVIEW

File: moveit_core/planning_scene/src/planning_scene.cpp [hunk 1]
```diff
@@ -387,20 +387,23 @@ void PlanningScene::clearDiffs()
...
+    if (parent_->getActiveCollisionDetectorName() != getActiveCollisionDetectorName())
     {
-      it.second->cenv_ = it.second->alloc_->allocateEnv(it.second->parent_->cenv_, world_);
-      it.second->cenv_const_ = it.second->cenv_;
+      ROS_ERROR_NAMED(LOGNAME, "Active collision detector of parent does not match this child scene's type");
+      return;
+    }
+
+    it.second->cenv_ = it.second->alloc_->allocateEnv(it.second->parent_->cenv_, world_);
+    it.second->cenv_const_ = it.second->cenv_;
```
Comment (AndyZe) [inline moveit_core/planning_scene/src/planning_scene.cpp:397]: These two lines were repeated in the if...else, so I moved them outside of it.

**Comment by AndyZe** [comment]
I'm going to reduce the scope of this PR to the small code simplification only and let #2499 handle the issue with `parent_` pointer.

File: moveit_core/planning_scene/src/planning_scene.cpp [hunk 2]
```diff
@@ -389,17 +389,15 @@ void PlanningScene::clearDiffs()
...
+
+      it.second->cenv_ = it.second->alloc_->allocateEnv(it.second->parent_->cenv_, world_);
+      it.second->cenv_const_ = it.second->cenv_;
     }
-    else
+    else  // This is the parent CollisionDetector
     {
       it.second->copyPadding(*parent_->active_collision_);
-
-      it.second->cenv_ = it.second->alloc_->allocateEnv(it.second->parent_->cenv_, world_);
```
Comment (AndyZe) [inline moveit_core/planning_scene/src/planning_scene.cpp:402]: problem here because `it.second->parent_` is null

File: moveit_core/planning_scene/src/planning_scene.cpp [hunk 3]
```diff
@@ -389,17 +389,15 @@ void PlanningScene::clearDiffs()
...
     if (it.second->parent_)
     {
-      it.second->cenv_ = it.second->alloc_->allocateEnv(it.second->parent_->cenv_, world_);
-      it.second->cenv_const_ = it.second->cenv_;
-
       it.second->cenv_unpadded_ = it.second->alloc_->allocateEnv(it.second->parent_->cenv_unpadded_, world_);
       it.second->cenv_unpadded_const_ = it.second->cenv_unpadded_;
+
+      it.second->cenv_ = it.second->alloc_->allocateEnv(it.second->parent_->cenv_, world_);
+      it.second->cenv_const_ = it.second->cenv_;
```
Comment (AndyZe) [inline moveit_core/planning_scene/src/planning_scene.cpp:396]: move these 2 lines down to match the order below: unpadded, then padded

File: moveit_core/planning_scene/src/planning_scene.cpp (hunk 2 above)
Comment (felixvd) [reply moveit_core/planning_scene/src/planning_scene.cpp:402]: I'm not sure I understand. Why is this line deleted?

**Review by felixvd — COMMENTED** [review]
Appreciate the improved comments, but don't know why a line of code was deleted.

File: moveit_core/planning_scene/src/planning_scene.cpp (hunk 2 above)
Comment (AndyZe) [reply moveit_core/planning_scene/src/planning_scene.cpp:402]: If you look at line 390, `if (it.second->parent_)` --> the pointer is null, so this will segfault.

That also means there is no parent CollisionDetector, so copying the parent's collision environment doesn't make sense.

I figure the original author copy/pasted this from L395 but forgot to update it.

**Review by jliukkonen — APPROVED** [review]

**Review by j-petit — APPROVED** [review]
Looks good to me.

**Review by tylerjw — APPROVED** [review]
lgtm

**Review by JafarAbdi — APPROVED** [review]
